In [24]:
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits, fetch_openml
from sklearn.cluster import AgglomerativeClustering, KMeans, dbscan
from sklearn.metrics import rand_score, silhouette_score, homogeneity_completeness_v_measure, v_measure_score
from sklearn.decomposition import TruncatedSVD
from sklearn.manifold import TSNE

In [3]:
data = np.array([
    [-1, -1],
    [-2, -1],
    [-1, -2],
    [0, 0],
    [2, 1],
    [2, 3]
])

In [4]:
AgglomerativeClustering().fit_predict(data)

array([0, 0, 0, 0, 1, 1], dtype=int64)

In [22]:
#KMeans(n_clusters=2, init=[[1,3],[2,1]], n_init=1).fit_predict(data,)
KMeans(n_clusters=2, init=np.array([0],[3]), n_init=1).fit_predict(data)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [37]:
dbscan(data,eps=100,min_samples=1)

(array([0, 1, 2, 3, 4, 5], dtype=int64),
 array([0, 0, 0, 0, 0, 0], dtype=int64))

In [36]:
silhouette_score(data,(0,0,0,1,1,1))

0.45993283428643883

In [38]:
TSNE(n_components=1).fit_transform(data)

array([[196.86476 ],
       [ 39.220425],
       [ 92.278175],
       [-20.800274],
       [143.76544 ],
       [256.7978  ]], dtype=float32)

In [39]:
TruncatedSVD(n_components=1).fit_transform(data)

array([[-1.41317178],
       [-2.09262138],
       [-2.14689397],
       [ 0.        ],
       [ 2.09262138],
       [ 3.56006575]])